<?php

/**
 * PluginzsBlogArticleTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginzsBlogArticleTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginzsBlogArticleTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginzsBlogArticleTag');
    }
}