<?php

/**
 * PluginzsBlogCommentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginzsBlogCommentTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginzsBlogCommentTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginzsBlogComment');
  }

  public function getListQuery()
  {
    $q = $this->createQuery('c')
            ->leftJoin('c.Article a');

    $q->addWhere('a.published_at IS NOT ?', null)
            ->orderBy('c.created_at DESC');

    return $q;
  }
}