<?php

/**
 * PluginzsBlogCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginzsBlogCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginzsBlogCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginzsBlogCategory');
    }
}