<?php

/**
 * PluginzsBlogTagTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginzsBlogTagTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginzsBlogTagTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginzsBlogTag');
  }

  public function retrieveTagsByNames(array $names)
  {
    $q = Doctrine_Query::create()
            ->from('zsBlogTag t')
            ->whereIn('t.name', $names);

    return $q->execute();
  }

  public function ajaxSearch($term)
  {
    $q = $this->createQuery('t')
            ->select('t.Id id, t.Name value')
            ->where('t.Name LIKE ?', '%'.$term.'%')
            ->limit(10);

    return $q->execute(array(), Doctrine::HYDRATE_ARRAY);
  }

  public function retrieveForRoute(Doctrine_Query $q)
  {
    $q->leftJoin($q->getRootAlias().'.Articles');

    return $q->fetchOne();
  }
}