<?php

/**
 * PluginzsBlogArticleTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginzsBlogArticleTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginzsBlogArticleTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginzsBlogArticle');
  }

  public function addJoinQuery(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.Category c')
            ->leftJoin($rootAlias . '.Tags t')
            ->leftJoin($rootAlias . '.CreatedBy u');
            //->leftJoin($rootAlias . '.Comments m');

    $q->addSelect($rootAlias.'.*, c.*, t.*, u.*');
    $q->addSelect('(SELECT COUNT(*) FROM zsBlogComment m WHERE m.article_id = '.$rootAlias.'.id) as num_comments');
    //$q->addSelect('COUNT(m.id) num_comments');
    //$q->groupBy($rootAlias.'.id');
            

    return $q;
  }

  public function getListQuery()
  {
    $q = $this->createQuery('a');

    $q = $this->addJoinQuery($q);

    $q->addWhere('a.published_at IS NOT ?', null)
            ->orderBy('a.published_at DESC');

    return $q;
  }

  public function retrieveForRoute(Doctrine_Query $q)
  {
    $q = $this->addJoinQuery($q);

    return $q->fetchOne();
  }
}