<?php

/**
 * PluginzsBlogTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginzsBlogTag extends BasezsBlogTag
{
  public function getArticleListQuery()
  {
    $ids = $this->getArticles()->getPrimaryKeys();

    /* @var $q Doctrine_Query */
    $q = Doctrine::getTable('zsBlogArticle')->getListQuery();

    $q->whereIn('a.id', $ids);

    return $q;
  }

}