<?php

/**
 * PluginzsBlogArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginzsBlogArticle extends BasezsBlogArticle
{
  public function getTagList()
  {
    return implode(', ', $this->getTags()->toKeyValueArray('id', 'name'));
  }

  public function getPublishedAt()
  {
    if (!$this->_get('published_at'))
      return;

    return date('Y-M-d', strtotime($this->_get('published_at')));
  }

  public function isPublished()
  {
    if ($this->_get('published_at'))
      return true;

    return false;
  }

  public function publish($force = false)
  {
    if (!$this->isPublished() || $force)
      $this->setPublishedAt(date('Y-m-d'), time());

    $this->save();
  }

  public function setTagList($names)
  {
    //remove existing tags
    $this->unlink('Tags', $this->Tags->getPrimaryKeys());

    if (empty($names))
      return;

    $existing_tags = zsBlogTagTable::getInstance()->retrieveTagsByNames($names);

    $new_tags = array_diff($names, $existing_tags->toKeyValueArray('id', 'name'));

    //add new tags
    foreach ($new_tags as $name)
    {
      $tag = new zsBlogTag();
      $tag->setName($name);
      $tag->save();

      $existing_tags->add($tag);
    }

    $this->link('Tags', $existing_tags->getPrimaryKeys());
  }

  /**
   * Required for zsSearch - returns true if published
   *
   * @return boolean
   */
  public function canSearch()
  {
    return $this->isPublished();
  }

  public function getContent()
  {
    return new zsDocument(parent::_get('content'));
  }

  public function getDescription()
  {
    $doc = $this->getContent();
    
    return $doc->stripTags()->truncate()->render();
  }
}