<?php

/**
 * PluginzsBlogArticleTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginzsBlogArticleTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginzsBlogArticleTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginzsBlogArticle');
  }

  public function retrieveArticlesByIds($ids)
  {
    $q = Doctrine_Query::create()
            ->from('zsBlogArticle a')
            ->whereIn('a.id', $ids);

    return $q->execute();
  }

  public function retrievePublishedArticlesQuery($category = null, $tag = null)
  {
    $q = Doctrine::getTable('zsBlogArticle')->createQuery('a');
    $q->where('a.published_at IS NOT ?', null)
            ->orderBy('a.published_at DESC');

    $q = $this->addJoinQuery($q);

    if ($category)
      $q->addWhere('a.category_id = ?', $category->getId());

    if ($tag)
      $q->addWhere('t.id = ?', $tag->getId());

    return $q;
  }

  public function retrievePublishedArticles($category = null, $tag = null)
  {
    return $this->retrievePublishedArticlesQuery($category, $tag)->execute();
  }

  /**
   * @param Doctrine_Query $q
   * @return Doctrine_Query
   */
  public function addJoinQuery(Doctrine_Query $q = null)
  {
    if (!$q)
      $q = Doctrine::getTable('zsBlogArticle')->createQuery('a');

    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.Category c')
            ->leftJoin($rootAlias . '.Tags t');

    return $q;
  }

  public function getLatestArticle($category = null, $tag = null)
  {
    $q = $this->retrievePublishedArticlesQuery($category = null, $tag = null);

    return $q->fetchOne();
  }
}