<?php

/**
 * PluginzsBlogCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginzsBlogCategory extends BasezsBlogCategory
{
  public function getArticles()
  {
    /* @var $q Doctrine_Query */
    $q = Doctrine::getTable('zsBlogArticle')->addJoinQuery();

    $q->where('c.id = ?', $this->id);

    return $q->execute();
  }
}